write_resume:
  description: >
    Given that the following lines are my resume (untill =+=) \n {my_resume} \n =+= create a tailored resume that fits the description of this role:  {role}.
  expected_output: >
    A complete resume.
  agent: researcher
